In [47]:
#execico 2
import numpy as np

Array_fatorial = np.arange(1,11)
print ('--------------Array-----------------')
print(Array_fatorial)

fator = 1

for i in Array_fatorial:
    fator =fator * i

Media =  fator / np.size(Array_fatorial)


print ('--------------Media do fatorial-----------------')

print(Media)
#print(np.mean(Array_fatorial))

print ('--------------Mediana--------------------------')

Mediana = np.median( Array_fatorial)

print(Mediana)

print ('--------------Desvio Padrao----------------------')

DesvP = np.std( Array_fatorial)

print(DesvP)

print ('--------------Soma----------------------')

Soma = np.sum( Array_fatorial)

print(Soma)


--------------Array-----------------
[ 1  2  3  4  5  6  7  8  9 10]
--------------Media do fatorial-----------------
362880.0
--------------Mediana--------------------------
5.5
--------------Desvio Padrao----------------------
2.8722813232690143
--------------Soma----------------------
55


In [48]:
Array_Soma = np.arange(1,11)
print ('--------------Array-----------------')
print(Array_Soma)

soma = 0

for i in Array_Soma:
    soma += i

print ('--------------Media do fatorial-----------------')
 
print(np.mean(Array_Soma))

print ('--------------Mediana--------------------------')

Mediana = np.median( Array_Soma)

print(Mediana)

print ('--------------Desvio Padrao----------------------')

DesvP = np.std( Array_Soma)

print(DesvP)

print ('--------------Soma----------------------')

Soma = np.sum( Array_Soma)

print(Soma)

--------------Array-----------------
[ 1  2  3  4  5  6  7  8  9 10]
--------------Media do fatorial-----------------
5.5
--------------Mediana--------------------------
5.5
--------------Desvio Padrao----------------------
2.8722813232690143
--------------Soma----------------------
55


In [52]:
Array = np.arange(1,11)
print ('--------------Array-----------------')
print(Array)
Array[1]=10
print (Array)

--------------Array-----------------
[ 1  2  3  4  5  6  7  8  9 10]
[ 1 10  3  4  5  6  7  8  9 10]


In [58]:
c = []
for i in range(len(a)):
c.append(a[i]*b[i])


IndentationError: expected an indented block (Temp/ipykernel_10892/766875896.py, line 3)